# Game Constants
WINDOW_WIDTH = 800
WINDOW_HEIGHT = 600
PLAYER_SIZE = 20
STICK_SIZE = 10
COLLECTION_RADIUS = 20
PLAYER_START_X = WINDOW_WIDTH // 2
PLAYER_START_Y = WINDOW_HEIGHT // 2
STICK_SPAWN_MARGIN = 50
